# -*- coding: utf-8 -*-
"""load_models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvppMardAxKSbZeL8MV-etBL5lCDgq0_
"""

from tensorflow.keras.models import load_model

print("Chargement des modèles ...")
print("Chargement de InceptionV3 avec masque ...")
mask_inception = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/masks_models/clf_model_inception")
print("Chargement de MobileNet avec masque ...")
mask_mobilenet = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/masks_models/clf_model_mobilenet1")
print("Chargement de ResNet50 avec masque ...")
mask_resnet50 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/masks_models/clf_model_resnet50")
print("Chargement de vgg16 avec masque ...")
mask_vgg16 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/masks_models/clf_model_vgg16")
print("Chargement de vgg19 avec masque ...")
mask_vgg19 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/masks_models/masks_vgg19")
mask_models={"InceptionV3":mask_inception,"MobileNet":mask_mobilenet,"ResNet50":mask_resnet50,"VGG16":mask_vgg16,"VGG19":mask_vgg19}

print("Chargement de InceptionV3 sans masque sans augmentation ...")
no_aug_inception = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/inceptionv3_no_aug")
print("Chargement de MobileNet sans masque sans augmentation ...")
no_aug_mobilenet = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/mobilenet_no_aug")
print("Chargement de ResNet50 sans masque sans augmentation ...")
no_aug_resnet50 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/resnet50_no_aug")
print("Chargement de VGG16 sans masque sans augmentation ...")
no_aug_vgg16 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/vgg16_no_aug")
print("Chargement de VGG19 sans masque sans augmentation ...")
no_aug_vgg19 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/vgg19_no_aug")
no_aug_models={"InceptionV3":no_aug_inception,"MobileNet":no_aug_mobilenet,"ResNet50":no_aug_resnet50,"VGG16":no_aug_vgg16,"VGG19":no_aug_vgg19}

print("Chargement de InceptionV3 sans masque avec augmentation ...")
aug_inception = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/inceptionv3_aug")
print("Chargement de MobileNet sans masque avec augmentation ...")
aug_mobilenet = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/mobilenet_aug")
print("Chargement de ResNet50 sans masque avec augmentation ...")
aug_resnet50 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/resnet50_aug")
print("Chargement de VGG16 sans masque avec augmentation ...")
aug_vgg16 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/vgg16_aug")
print("Chargement de VGG19 sans masque avec augmentation ...")
aug_vgg19 = load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/no_mask_models/vgg19_aug")
aug_models={"InceptionV3":aug_inception,"MobileNet":aug_mobilenet,"ResNet50":aug_resnet50,"VGG16":aug_vgg16,"VGG19":aug_vgg19}

print("Chargement du modèle U-Net ...")
unet=load_model("/content/drive/MyDrive/Soumaya - PFE/results/saved_models/segmentation/saved_unet")
print("Le chargement des mdèles est terminé avec succès.")